<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<yml_catalog date="2024-05-26 12:10">
  <shop>
    <name>Я стиралкин</name>
    <company>ИП Кулевец Вячеслав Васильевич</company>
    <url>https://www.i-stiralkin.by/</url>
    <email>i-stiralkin@yandex.by</email>
    <currencies>
      <currency id="BYN" rate="1" />
    </currencies>
    <categories>
      <category id="1">Исполнитель</category>
      <category id="11" parentId="1">Стиральные машины</category>
      <category id="12" parentId="1">Стирально-сушильные машины</category>
      <category id="13" parentId="1">Cушильные машины</category>
    </categories>
    <!--Добавили sets по сравнению с обычным YML-->
    <sets>
      <set id="s1">
        <name>Ремонт бытовых стиральных и стирально-сушильных машин любой марки и возраста в Минске</name>
        <url>https://worker.sample.s3.yandex.net/213-moscow/category/remont-i-stroitelstvo--1344</url>
      </set>
    </sets>
    <offers>
      <offer id="923950riserpk">
        <name>Дмитрий А.</name>
        <url>https://www.i-stiralkin.by/#prices-section</url>
        <picture>https://www.i-stiralkin.by/resources/logo.png</picture>
        <price from="true">30</price>
        <currencyId>BYN</currencyId>
        <sales_notes>(при отказе от ремонта или отсутствии поломки)</sales_notes>
        <categoryId>1</categoryId>
        <set-ids>s1</set-ids><!--Можно указать и несколько сетов через запятую-->
        <picture>https://www.i-stiralkin.by/resources/logo.png</picture>
        <description>Выезд и диагностика</description>
        <adult>false</adult>
        <expiry>P5Y</expiry>
        <!--Этот набор параметров обязателен-->
        <param name="Рейтинг">5.0</param>
        <param name="Число отзывов">17</param>
        <param name="Годы опыта">11</param>
        <param name="Регион">Минск</param>
        <param name="Конверсия">1.935</param><!--Это произвольное число, оно не обязано быть от 0 до 1-->
        <!--Этот набор параметров необязателен-->
        <param name="Ссылка на телефон">https://www.i-stiralkin.by/tel:+375293589131</param>
        <param name="Выезд на дом">да</param>
        <param name="Работа по адресу">нет</param>
        <param name="Выполняется удаленно">нет</param>
        <param name="Работа по договору">да</param>
        <param name="Наличный расчет">да</param>
        <param name="Безналичный расчет">да</param>
      </offer>
      <offer id="923950riserue"><!--И ещё одно предложение от того же исполнителя (отличается урлом, ценами, сетом)-->
        <name>Дмитрий А.</name>
        <url>https://www.i-stiralkin.by/#prices-section</url>
        <picture>https://www.i-stiralkin.by/resources/logo.png</picture>
        <price from="true">30</price>
        <currencyId>BYN</currencyId>
        <sales_notes>(при отказе от ремонта или отсутствии поломки)</sales_notes>
        <categoryId>1</categoryId>
        <set-ids>s1</set-ids><!--Можно указать и несколько сетов через запятую-->
        <picture>https://www.i-stiralkin.by/resources/logo.png</picture>
        <description>Выезд и диагностика</description>
        <adult>false</adult>
        <expiry>P5Y</expiry>
        <!--Этот набор параметров обязателен-->
        <param name="Рейтинг">5.0</param>
        <param name="Число отзывов">17</param>
        <param name="Годы опыта">11</param>
        <param name="Регион">Минск</param>
        <param name="Конверсия">1.935</param><!--Это произвольное число, оно не обязано быть от 0 до 1-->
        <!--Этот набор параметров необязателен-->
        <param name="Ссылка на телефон">https://www.i-stiralkin.by/tel:+375293589131</param>
        <param name="Выезд на дом">да</param>
        <param name="Работа по адресу">нет</param>
        <param name="Выполняется удаленно">нет</param>
        <param name="Работа по договору">да</param>
        <param name="Наличный расчет">да</param>
        <param name="Безналичный расчет">да</param>
      </offer>
    </offers>
  </shop>
</yml_catalog>
